version: '3'
services:
  regalia-mysql:
    image: 'mysql:8.0'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=Regalia_Ordering_System
    ports:
      - "3307:3306"
  regalia-spring-container:
    image: regalia-spring-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://regalia-mysql:3306/Regalia_Ordering_System?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: "./"
      dockerfile: "DockerFile"
    depends_on:
      - regalia-mysql
