CREATE TABLE `Regalia_Ordering_System`.`USERS` (
  `USER_ID` BIGINT(4) NOT NULL AUTO_INCREMENT,
  `EMAIL` VARCHAR(45) NULL,
  `USERNAME` VARCHAR(45) NULL,
  `FIRST_NAME` VARCHAR(45) NULL,
  `LAST_NAME` VARCHAR(45) NULL,
  `PASSWORD` VARCHAR(64) NULL,
  `ENABLED` TINYINT NULL,
  `PHONE_NUMBER` INT NULL,
  `WEIGHT` INT NULL,
  `HEIGHT_FEET` INT NULL,
  `HEIGHT_INCHES` INT NULL,
  `GRANTING_INSTITUTION` VARCHAR(45) NULL,
  `GRANTING_CITY` VARCHAR(45) NULL,
  `LAST_UPDATED` VARCHAR(45) NULL,
  `CEREMONY_ID` BIGINT(4) NULL,
  `CAP_SIZE_ID` BIGINT(4) NULL,
  `DEGREE_ID` BIGINT(4) NULL,
  `DEPARTMENT_ID` BIGINT(4) NULL,
  `STATE_ID` BIGINT(4) NULL,
  PRIMARY KEY (`USER_ID`),
  INDEX `CEREMONY_ID_FK_idx` (`CEREMONY_ID` ASC) VISIBLE,
  INDEX `CAP_SIZE_ID_FK_idx` (`CAP_SIZE_ID` ASC) VISIBLE,
  INDEX `DEGREE_ID_FK_idx` (`DEGREE_ID` ASC) VISIBLE,
  INDEX `DEPARTMENT_ID_FK_idx` (`DEPARTMENT_ID` ASC) VISIBLE,
  INDEX `STATE_ID_FK_idx` (`STATE_ID` ASC) VISIBLE,
  CONSTRAINT `CEREMONY_ID_FK`
    FOREIGN KEY (`CEREMONY_ID`)
    REFERENCES `Regalia_Ordering_System`.`CEREMONY` (`CEREMONY_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CAP_SIZE_ID_FK`
    FOREIGN KEY (`CAP_SIZE_ID`)
    REFERENCES `Regalia_Ordering_System`.`CAPSIZE` (`CAPSIZE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DEGREE_ID_FK`
    FOREIGN KEY (`DEGREE_ID`)
    REFERENCES `Regalia_Ordering_System`.`DEGREE` (`DEGREE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DEPARTMENT_ID_FK`
    FOREIGN KEY (`DEPARTMENT_ID`)
    REFERENCES `Regalia_Ordering_System`.`DEPARTMENT` (`DPT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `STATE_ID_FK`
    FOREIGN KEY (`STATE_ID`)
    REFERENCES `Regalia_Ordering_System`.`STATES` (`STATE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
